### ISSUE TITLE
Improve MongoDB Database Support

### ISSUE THREAD

**Issue by Manikya-Sharma** [Manikya-Sharma/stusome-v2#9]
## Problems

1.  Everything is excessively flattened which has led to problems in maintaining referential integrity
2. Data access is too slow and inefficient
3. Poor error handling and improper response codes from existing api

## Available solutions

1. Make the existing database and data fetching more efficient
2. Use a different database than MongoDB, maybe SQL based instead of NoSQL

# Tasks

- [x] Find out how to store multimedia data in mongoDB (Done by @Nikhil-Sharma-06404 )
- [ ] Improve existing schema to allow support for - mutimedia, upvote/downvove, report
- [ ] Export existing database to new database
- [ ] Make all the necessary changes in frontend ( @Manikya-Sharma )
- [ ] Make all the necessary changes in backend (@Manikya-Sharma )
